### ISSUE TITLE
Unable to load addon script from path:

### ISSUE THREAD

**Issue by tzwel** [Pieeer1/GodotVoipNet#16]
The addon won't load. Errors out with:
`No loader found for resource: res://addons/GodotVoipNet/Plugin.cs.`

![image](https://github.com/Pieeer1/GodotVoipNet/assets/39600182/407cb831-cb03-4e2c-bedd-4f9ee3309705)
![image](https://github.com/Pieeer1/GodotVoipNet/assets/39600182/5f171963-dcda-4a79-8b8c-fd5c563865b0)

**Comment by Pieeer1** [comment]
What version are you using? (Need clarification here because I forgot to update the cfg file) Additionally this issue can happen when the addons folder is capitalized

**Comment by Pieeer1** [comment]
Closing this as idle. 

I was not able to replicate with a fresh install.
