### ISSUE TITLE
Consider using e.g. VS2022 Test adaptor compatible unit tests

### ISSUE THREAD

**Issue by GeorgeS2019** [Pieeer1/GodotVoipNet#8]
using the [latest](https://github.com/MikeSchulze/gdUnit4Mono/pull/37) gdUnit4API **TestAdaptor** on VS2022

![Z0nhScGr3J](https://github.com/MikeSchulze/gdUnit4Mono/assets/49812372/7d2ed607-0750-4b6e-80f7-e5913aec040e)

**Comment by Pieeer1** [comment]
This is a good recommendation, currently working on stereo audio and some better integration testing. I’ll close this once I add some unit tests as well.

**Comment by GeorgeS2019** [comment]
@MikeSchulze

I simply clone the branch
I already define GODOT_BIN
I build the project and the test appear. 

![image](https://github.com/Pieeer1/GodotVoipNet/assets/49812372/c6b5436c-2b63-4235-96ec-25406dcc01b2)

**Comment by Pieeer1** [comment]
Added unit tests in https://github.com/Pieeer1/GodotVoipNet/pull/12

**Comment by MikeSchulze** [comment]
> Added unit tests in #12

Check out my comments on the PR, I will add one more piece of information on the generated files to clarify this.

**Comment by Pieeer1** [comment]
> > Added unit tests in #12
> 
> Check out my comments on the PR, I will add one more piece of information on the generated files to clarify this.

This has been handled in #13
